### ISSUE TITLE
Deprecation DateTime::__construct() Passing null in class-rest.php

### ISSUE THREAD

**Issue by RodCyb3Dev** [LianaTechnologies/lianamailer-gf#4]
This plugin is causing deprecation notice on both the backend and frontend due to passing `null` to the `DateTime` constructor in the plugin.

**Deprecation Notice:**
Deprecated: DateTime::__construct(): Passing null to parameter `#1` ($datetime) of type string is deprecated in /lianamailer-gf/includes/Mailer/class-rest.php on line 133

```php
$datetime  = new \DateTime( null, new \DateTimeZone( 'Europe/Helsinki' ) );
```

**Expected Behavior:**
No deprecation notice should appear.

**Actual Behavior:**
The first parameter of the DateTime constructor is expected to be a string, but null is provided. This leads to unexpected behavior or errors, like deprecation notice appears on both backend and frontend.

**Environment:**
- PHP Version: 8.0
- WordPress Version: 6.5.4
- Plugin `lianamailer-gf` Version: 1.0.57

**Additional Context:**
The issue is caused by passing `null` to the `DateTime` constructor. The fix involves passing an empty string or the current date and time instead of `null`.

**Proposed Fix**:
Replace the current line with:

```php
$datetime = new \DateTime('now', new \DateTimeZone('Europe/Helsinki'));
```

**Comment by lianatech-sami-siuvatti** [comment]
Handled in https://github.com/LianaTechnologies/lianamailer-gf/pull/3

Thank you for contributing!
